/********************************************************************
* _ROOT_DICT.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _ROOT_DICT.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT();
extern void G__cpp_setup_inheritance_ROOT_DICT();
extern void G__cpp_setup_typetable_ROOT_DICT();
extern void G__cpp_setup_memvar_ROOT_DICT();
extern void G__cpp_setup_global_ROOT_DICT();
extern void G__cpp_setup_memfunc_ROOT_DICT();
extern void G__cpp_setup_func_ROOT_DICT();
extern void G__set_cpp_environment_ROOT_DICT();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GNuMcMainFrame.h"
#include "FastSimCherenkov.h"
#include "FastSimScintCalo.h"
#include "MCTruthDisplay.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICTLN_TClass;
extern G__linked_taginfo G___ROOT_DICTLN_TBuffer;
extern G__linked_taginfo G___ROOT_DICTLN_TMemberInspector;
extern G__linked_taginfo G___ROOT_DICTLN_TObject;
extern G__linked_taginfo G___ROOT_DICTLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_string;
extern G__linked_taginfo G___ROOT_DICTLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICTLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICTLN_TQObject;
extern G__linked_taginfo G___ROOT_DICTLN_TGObject;
extern G__linked_taginfo G___ROOT_DICTLN_TGWindow;
extern G__linked_taginfo G___ROOT_DICTLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G___ROOT_DICTLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICTLN_TGFrame;
extern G__linked_taginfo G___ROOT_DICTLN_TGCompositeFrame;
extern G__linked_taginfo G___ROOT_DICTLN_TGLayoutHints;
extern G__linked_taginfo G___ROOT_DICTLN_TGMatrixLayout;
extern G__linked_taginfo G___ROOT_DICTLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICTLN_TGMainFrame;
extern G__linked_taginfo G___ROOT_DICTLN_TGGroupFrame;
extern G__linked_taginfo G___ROOT_DICTLN_TGPictureButton;
extern G__linked_taginfo G___ROOT_DICTLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICTLN_TGTab;
extern G__linked_taginfo G___ROOT_DICTLN_TGTextEdit;
extern G__linked_taginfo G___ROOT_DICTLN_TGStatusBar;
extern G__linked_taginfo G___ROOT_DICTLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICTLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G___ROOT_DICTLN_TFile;
extern G__linked_taginfo G___ROOT_DICTLN_TTree;
extern G__linked_taginfo G___ROOT_DICTLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_genie;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLEGEvGenMode;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLEKinePhaseSpace;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLERefFrame;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G___ROOT_DICTLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLTarget;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLInitialState;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLEInteractionType;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLEScatteringType;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLProcessInfo;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLEKineVar;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLKinematics;
extern G__linked_taginfo G___ROOT_DICTLN_maplEgeniecLcLEKineVarcOdoublecOlesslEgeniecLcLEKineVargRcOallocatorlEpairlEconstsPgeniecLcLEKineVarcOdoublegRsPgRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLEResonance;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLXclsTag;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLInteraction;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLEGHepStatus;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLGHepRecord;
extern G__linked_taginfo G___ROOT_DICTLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G___ROOT_DICTLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLEventRecord;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLNtpMCRecHeader;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLNtpMCEventRecord;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLmasterclass;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLmasterclasscLcLMCTruthDisplay;
extern G__linked_taginfo G___ROOT_DICTLN_geniecLcLmasterclasscLcLGNuMcMainFrame;

/* STUB derived class for protected member access */
